### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by KevinSmarts** [comment]
Using desktop was meant to make this so much easier /sigh

**Comment by Thekingofsweden** [comment]
Heh. I'm actually not having too many problems with it, but I think part of that is the fact that I do all my editing directly on the files via notepad++, instead of using qgen.

**Comment by KevinSmarts** [comment]
That part I had sorted, not a problem. The thing is it keeps changing the repo I'm trying to commit to, to the 1.1.3 + patches, and I keep failing to catch it when it does.

**Comment by Thekingofsweden** [comment]
Ah. There is probably a setting on desktop for that, or possibly within your repo. Maybe you need to change your default branch?

**Pull request merged**
