### PR TITLE
New bimbo system

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
Ooo, this bimbo thing is interesting. Great job with the commenting on it too.
As an aside, did you happen to validate the vnesh calculation while you were in there? I know there have been occasional questions/concerns about it, it might be a good time to take a look at it (and maybe document how it works).

**Comment by KevinSmarts** [comment]
It's pretty hard to reach 15 points, I cheatmenu the hell out of it to get there. I'll go through it now and make sure it's counting everything. Most of the comments I copied from Veedanyas .txt

**Comment by KevinSmarts** [comment]
Until we seed more exhibitionism, it's really hard to get. You'd need atleast some surgery, but that does fit with the character of a bimbo. I don't know, might try and get some feedback in forum.

**Comment by Thekingofsweden** [comment]
It's one of those things that you can't really know until it's playtested.

**Pull request merged**
