### PR TITLE
V1.2.2

### PR DESCRIPTION
**Pull request by KevinSmarts**
Stupid computer :)

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
Study is a legitimate option for non-students?

**Comment by KevinSmarts** [comment]
Good point

**Comment by Thekingofsweden** [comment]
Nice. Though this does show one of those situations where the variables are just out of control. 2 variables for student status. ug. Should probably be one, with perhaps a 0 for not a student, -1 for kicked out, 2 for graduate. Something like that maybe. Down the line though.

**Comment by KevinSmarts** [comment]
to be fair, one is school and the other uni.

**Comment by Thekingofsweden** [comment]
True. I think I was thinking of the variable for when you are kicked out of school.

**Pull request merged**
