### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
I wonder about when locations with dynamic functions in them need to be called. If it's just once, it could be done in startup or something, assuming that that stays through loads.

**Comment by KevinSmarts** [comment]
Well, something like this might be worth having a gs to it in stat, but i'll try and get it all in and working first.

**Comment by WonderDog** [comment]
Dynamics are a variable and stored in the save file and only need to 
initialised once unless you kill the variable.

I normally use gosub to the dynamic initialisation location in the 
'start' and 'loadg' locations.  I also have a test to skip if loaded at 
the top of my dynamic code.

There is a problem with the save and loading the game state (current 
location) if the game is saved when currently executing dynamic code 
more than one level deep.

**Comment by Thekingofsweden** [comment]
Ah, that explains a lot actually.

**Comment by WonderDog** [comment]
The current location or dynamic is copied into a currently running code memory location and this is saved or loaded to disk with the stack, screens and variables.  This is why changes to the location or dynamic are not apparent on a load game till you force the location to reinitialise.

I am pretty sure the game stores the current address pointer on the stack as a memory offset of some base such as the entry point of the code or location. But dynamics are a variable and will have a different address after reloading. This breaks the pointer for dynamics. The currently executing dynamic will be ok as it is loaded from the save file but it will be able to return to locations but not to calling dynamic code.

**Pull request merged**
