### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
The Lariska quest is set up so that, after winning the fight with her, the next event starts seven days later. It does that by setting lariskaQwestStart = daystart + 7, so the check in gdksport is actually correct as <=. It's a bit of a weird spot that it's in, since you only see it happen when leaving the gym when all the conditions are met, so it's not the most obvious thing, but it is correct as it was.

**Comment by KevinSmarts** [comment]
It's meant to trigger within a week, not after a week from what everyone can tell. In fact if it doesn't players are finding that Christina events fire and it won't trigger at all. So it has to be when the variable is greater than daystart.

**Comment by Thekingofsweden** [comment]
I don't have access to the full code base where I am right now, so I don't remember what it is initially set to, but I suspect it's set extremely high (999999 or something like that). Assuming that, let us assume that you fight with her on day 30. When you win that fight, lariskaQwestStart is set to 37 (daystart + 7). On day 38 or later, lariskaQwestStart is <= daystart. If you can, check to see what lariskaQwestStart is intially set to.

**Comment by KevinSmarts** [comment]
It's 0, checked it in town, new start

**Comment by Thekingofsweden** [comment]
Well, that's weird then. I'm just surprised because I am certain that I've seen the quest work. That might have been on the Russian version though, since I do run both to compare functionality on occasion.
I still don't know how a >= will work though. Using my previous example, but with a >=, you will have exactly one week to have the next event trigger before it can never trigger again.

**Comment by KevinSmarts** [comment]
It's the same in every version, I've opened them all in qgen to check, However, Morphuret has been having a nightmare getting it to fire, and proposed this change saying it has fixed it. Also, it doesn't work on 1.2.3 according to peolple on tempgrs help thread who have been in same situation.

**Comment by Thekingofsweden** [comment]
Ah. I'll have to give it a run when I have some time (and am at home, since running this game on my work PC is probably not a good idea).

**Comment by KevinSmarts** [comment]
Yeah, probably not :)

**Comment by Thekingofsweden** [comment]
Ok, going through the quest.
The way I am seeing this progresses is:
Win the city competition race on Saturday outside the school 3 times. This sets zverevaQW = 1
You can then eavesdrop on a Wednesday or Friday at the school after gym class. This sets zverevaQW = 2, or 3 if you enter the room.
At zverevaQW = 2 or 3, you have the option to spread rumors about her in school. This sets zverRageQW = 1.
After school, with zverRageQW = 1, you fight her. If you lose, zverRageQW = 10. If you win, which is what we are talking about, zverSlutQW = 1 and lariskaQwestStart = daystart + 7.
Now the step we are dealing with. In the gym, on a Thursday, with a relationship at 80 or higher with Lariska, and where lariskaQwestStart <= daystart (7 or more days after the previous step).

I just ran through all of those steps with the version downloaded from the repo (without this pull request), and it worked just fine.

**Comment by KevinSmarts** [comment]
You're the boss :)
I haven't had a chance to play it through, but will see about hinting at the right steps in the text.

**Comment by Thekingofsweden** [comment]
It is a rather odd setup I will admit. I suspect the problem that people are having is the lack of reputation with her. The whole lariskaQwestStart thing is actually handled rather oddly too, since it sets it to daystart  + 7 and compares against daystart, where most post date checks (that I can think of) are done in the pattern of lariskaQwestStart = daystart with a comparison of <= daystart + 7. Same effect in the end, just written differently.

**Pull request merged**
