### PR TITLE
fix?

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by KevinSmarts** [comment]
I tried to add wear to clothing, and it doesn't work, plus I can't workout how to do it. Everything I tried the clothes remain at full strength.

**Comment by Thekingofsweden** [comment]
How/when do you want it to apply?

**Comment by KevinSmarts** [comment]
'starenie' is called once at midnight, it is meant to lower clothing strength by 1, but either it does not, or it immediately reverts.

**Comment by Thekingofsweden** [comment]
Should it be clothing that is currently worn? If so, that might be because the clothing is being removed when you go to bed.

**Comment by KevinSmarts** [comment]
I tried to circumvent that, but whenever you call the 'starenie' file, it does nothing.

**Comment by Thekingofsweden** [comment]
Well, you should determine first if it's the file itself or if there is something else that is resetting it. The simplest way to do that would be to use the dynamic input command in the cheat menu. Set a piece of clothing to a lower durability, then move around a bit and see if it changes back to full.

**Comment by KevinSmarts** [comment]
Oh, that makes it clearer. The clothes aren't showing the correct strength in the wardrobe. I wear an outfit @ -20 but the wardrobe lists it at 60. Also the checks for worn out don't kick in.

**Comment by Thekingofsweden** [comment]
Ah. That would do it.

**Comment by KevinSmarts** [comment]
it seems so are using <<$ARGS[1]>>H[<<ARGS[2]>>
and so use <<$ARGS[2]>>H[<<ARGS[3]>>
neither show up correct here, lol
Don;t suppose you know which one is correct?

**Comment by Thekingofsweden** [comment]
I just downloaded and built the latest build and the cabinet seems to be working fine for me.
These are the steps I did to test.
Started a new game, alternate start (because it's less to click through).
Clicked cabinet, changed to sportswear.
Opened the cheat menu, clicked Dynamic Input Command, and entered "jeansH[1]" (without the quotes obviously). This dumped the value of the strength of jeans1 (which was 100) to the main window.
Clicked dynamic input command again, this time typing "jeansH[1]=80". This would set the strength value of jeans1 to 80. Clicking on the cabinet showed the correct value.
Used dynamic input command again, this time using "jeansH[1]=0". This sets strength to 0, breaking the item. Using the cabinet and clicking on view for the jeans shows that it won't let me wear them.

**Comment by KevinSmarts** [comment]
Thanks, now the original call for 'starenie' will actually work as intended.

**Comment by Thekingofsweden** [comment]
Victory! Excellent job figuring that out. And it was a nice little learning experience for the both of us.
And don't feel bad about the confusion, I nearly cried when I was trying to figure that damn code out the first time.

**Pull request merged**
