### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
Getting rid of more one time use rand variables makes me so happy.

=> should really be changed to >= . They work identically in this language, but it's both annoying to have two different sets of syntax for the same thing and some languages use => as an assigner, so it's confusing for people (like myself) to see it as a comparison. Not that you are to blame obviously, since it was already that way, but I'd suggest changing any of those that you see as you go.

if soniaPS => 1 and hour <= 23 and (week < 6 and hour >= 16 or week >= 6 and hour >= 10):
Is a significant improvement over the original line, but the optimal way to write it would be
if soniaPS >= 1 and hour <= 23 and ((week < 6 and hour >= 16) or (week >= 6 and hour >= 10)):
The extra parens prevent any confusion. The same would apply for the later if block that you changed.

**Comment by KevinSmarts** [comment]
Before you say it, I know. Dynamic eat and drink. :)

**Comment by Thekingofsweden** [comment]
Heh, I totally would have said that.

Also, why did you change the if in club to the less clean version?

**Comment by KevinSmarts** [comment]
OOPS!

**Pull request merged**
