### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
Does it need an exit after the too drunk to dance call?

**Comment by KevinSmarts** [comment]
I don't think so, the following is elseif and else, so shouldn't be called. I'll play-test it

**Comment by KevinSmarts** [comment]
Damn! You're good

**Comment by Thekingofsweden** [comment]
Why are you making it only have a 50/50 shot? Also, if it is supposed to be 50/50, you may need to change it to an if block, as it is it will exit out if it gets inside the alko >= 4 block even if it doesn't call the dynamic.
Are you perhaps really meaning to do:
if alko >= 4 and rand(0, 1): ?

**Comment by KevinSmarts** [comment]
This is what it is meant to do, I've checked. I didn't want the else to trigger as that wouldn't make sense, so it had to be in the alko > 4. The exit does stop you having a choice in the matter, which is intended. However making it 50/50 stops it being really annoying (I hope)

**Comment by Thekingofsweden** [comment]
Ah, that makes sense. The elseif after it should be just changed to alko < 0, since it's obviously already < 4.

**Pull request merged**
