### PR TITLE
1.2.2 compliance

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
Holy crap. I'm going to have to take some time to go through this, as there are merge conflicts. And I really need to figure out how to use the tools right for that.

**Comment by KevinSmarts** [comment]
Sorry, I didn't mean to push everything, yet. User error - DO NOT MERGE - at this time.

**Comment by Thekingofsweden** [comment]
Glad I didn't then. Are you thinking about doing another branch?

**Comment by KevinSmarts** [comment]
Not if I can avoid it, the idea was to bring in all the extra 1.2.2 stuff and maintain our text, mods and fixes. Once it's all done it would be a safe all-in-one 1.2.2 upgrade for your branch.

**Comment by Thekingofsweden** [comment]
Well, I could spawn a branch off of this one, and you could do the merging with that. Then, once we are certain it's all good, it's a hell of a lot easier to merge back in.

**Comment by KevinSmarts** [comment]
If that's easier for you, then it's all good. I usually just look at the stuff on Github, press buttons randomly and pray I didn't break anything.

**Comment by Thekingofsweden** [comment]
Having it on a separate branch just means that you can do commits as you finish stuff up, and once we decide that all of the commits on that branch are done, then we worry about merging it to the parent branch. At the same time, other people (or you) can make other changes, and it's just a matter of merging them together. Not really my strong suit, but that's mostly from having to rarely do it. It's just tedious for the most part.

**Comment by KevinSmarts** [comment]
Perfect and appreciate the help, thank you.

**Pull request closed without merging**
