### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
My kingdom for a switch statement. All those rand(0, x) values and then giant if chains makes me so sad.

**Comment by KevinSmarts** [comment]
I already reformatted it, gave it a quick clean up, a couple of bug fixes and introduced it to the word 'else' and it's still a horrible mess.

**Comment by Thekingofsweden** [comment]
Not your fault, more a limitation of the language.

**Comment by KevinSmarts** [comment]
I know it's impossible to convey tone in text, but I meant that despite what I had done it was still a mess. The broken down turd I copied from 1.2.2 was a disgrace and I feel embarrassed on behalf of all involved in it's production. I have done what needed to be done to get it working, but if I had written it, I wouldn't consider it ready to submit.

**Comment by Thekingofsweden** [comment]
Ah. Fair enough. We've all submitted crap code before, and we will do it again, and we will be sad about it every time.

**Pull request merged**
