### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
I'm starting to wonder if it would be worth it to simply do a search for certain patterns, like for example digits and an = without a space, and fix all of those in one fix. I'll have to play around with my grep tools to see what I can do. If I can get several of the common patterns, it would cut down the amount of trivial cleanup that needs to be done.

**Comment by KevinSmarts** [comment]
That would be very handy.

**Comment by WonderDog** [comment]
I used to do that before the QSP tools when translating.  I had about a dozen fixes to simplify extracting strings for translating.

One tip was as replace all double quotes with Unicode double quote symbol and when finished reverse the changes as I found the double quotes were breaking some matches.

I also use "QSP_Analyser.exe"  to find problem Locations, Variables, Objects and Menus as some syntax checking. (syntax checking can problems with dynamic code, *=, \= and some arrays)

The only problem is it is a Russian tool but you can copy the output into google to translate.

**Comment by Thekingofsweden** [comment]
Interesting. I'll have to look at it. I've had that problem with it breaking code before in other coding languages, so it really might be worth it to just do it semi-manually, using a grep tool or something. More tedious certainly, but at least it won't introduce bugs.

**Pull request merged**
