### PR TITLE
Update sistersleep

### PR DESCRIPTION
**Pull request by KevinSmarts**
Major change :)

### CODE REVIEW

**Comment by KevinSmarts** [comment]
I know it doesn't look it now, but that comment was hilarious when I was just adding a '>'

**Comment by Thekingofsweden** [comment]
Hahahahahahaha

**Comment by Thekingofsweden** [comment]
I'm debating making a series of 'locations' that just contain things like say one for the common bathroom stuff. Once it's more stable of course.

**Comment by KevinSmarts** [comment]
It would have so many conditionals for the pictures and facilities that it although saving space, it would be more processor hungry. Maybe stick the various actions into a dynamic like the shower and piercings?

**Comment by Thekingofsweden** [comment]
Ah. I was thinking of doing dynamics for the individual things, not the bathroom as a whole. Like one for cleaning one's face, which would be used anywhere that is an option, and the dynamic itself would figure out if there was anything to clean and only display the action in that event. So an individual bathroom would have a chain of the ones that are allowed there.

**Pull request merged**
