### PR TITLE
fixes for issue #23 by cleaning up glife.qproj a little

### PR DESCRIPTION
**Pull request by morgolon**
Did three things in this pull request, to address #23:
1. Commented out the `Menu.{Treatment}` location which does not have a corresponding location file, as far as I can tell; the file name/location name would have to change to exclude the brackets.
2. Added a few missing locations for which there were in fact files
3. Removed non-latin characters (been meaning to do that for a while now) -- this one is non-essential, consider it a bonus :)

### CODE REVIEW

**Comment by WonderDog** [comment]
"Menu.{Treatment}" exists in the game and is used.  The python scripts do not split the file because of the" {}". It is attached to Menu.Destroy location.  

You need to reverse this change in "glife.qproj" as it will be added next time you save in in qgen.exe

**Comment by morgolon** [comment]
@WonderDog maybe we should rename this location so that it can get its own file that doesn't use characters that conflict with the file system? Unless there's a reason to keep the brackets that I'm currently missing...

**Comment by WonderDog** [comment]
All the `Menu` locations are a part of a code libary that we should not need to touch as there is no russian to translate.

I would leave it alone as it caused no harm being in `Menu.Destroy`.  Just need to make sure it is in the project file so it won't get added to the end of the project file next time someone saves `glife.qsp` in the editor.

**Comment by morgolon** [comment]
I agree that it doesn't cause any harm, but it does cause confusion -- it confused me, at least. I'll send a separate PR about this, we can discuss it there

**Comment by WonderDog** [comment]
Simplest might be to fix the python split and join scripts.

**Pull request merged**
