### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by KevinSmarts**

### CODE REVIEW

**Comment by Thekingofsweden** [comment]
I never liked how bimbo clothing worked. I feel like maybe it should be another clothing type, with clothing that works with the rest of the clothing system.

**Comment by KevinSmarts** [comment]
I said exactly that! I'll add it to the list of things I'll probaly never get around to doing, but really should :)

**Comment by Thekingofsweden** [comment]
Ha! I should really do it, since I'm the one who rewrote the clothing system a while back. But I should also finish the Lariska stuff, and I'm frankly just too burned out on code right now. Stupid work.

**Comment by KevinSmarts** [comment]
Relax and chill out, you mental health is far more important than the game, besides Lariska has been broken for as long as anyone can remember, it's hardly time critical. When you are feeling abit more up for it, a new release would take a lot less head scratching and have a bigger impact, but that doesn't mean do it now.

**Comment by Thekingofsweden** [comment]
I actually use working on the game as a stress reliever, but I've been fighting headaches for days. Not real bad ones, but bad enough to bother me all day and make it hard to sleep at night.

**Comment by KevinSmarts** [comment]
Work isn't a stress reliever, take things slow, play a game or two and don't worry about glife, nothing is going to combust or fail if left unattended for a few days, and hope you feel better soon.

**Comment by Thekingofsweden** [comment]
Much appreciated, and you are right, I need to stop worrying so much.

**Pull request merged**
